[package]
name = "secs"
version = "0.2.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.14.2", default-features = false }
secs_macros = { path = "./secs_macros" }

[dev-dependencies]
rand = "0.8.5"

[lints.rust]
unsafe_code = "forbid"
